version: '3.8'
services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:7.2.4-alpine
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:8.16.1
    container_name: elastic_container
    environment:
        - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - app-net

volumes:
  db:
    driver: local
  es-data:
    driver: local

networks:
  app-net:
    driver: bridge
